[package]
name = "example-gui"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
eframe = "0.27.2"
userprompt = { path = "../../userprompt", features = ["egui"] }
simple_logger = "4.3.3"